config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"

  get 'users/new', to: 'users#new'
  get 'users/index', to: 'users#index'
  post 'users/create', to: 'users#create'

  get 'session/new', to: 'session#new'
  post 'session/create', to: 'session#create'
  post 'session/destroy', to: 'session#destroy'

  get 'restaurants/index', to: 'restaurants#index'
  get 'restaurants/all', to: 'restaurants#all'
  get 'restaurants/show', to: 'restaurants#show'
  post 'restaurants/create', to: 'restaurants#create'
  post 'restaurants/update', to: 'restaurants#update'
  get  'restaurants/food_items', to: 'restaurants#food_items'
  get 'restaurants/search', to: 'restaurants#search'

  post 'food_items/add', to: 'food_items#add'
  post 'food_items/change_item_lock', to: 'food_items#change_item_lock'
  post 'food_items/delete', to: 'food_items#delete'
  post 'food_items/update', to: 'food_items#update'

  get 'orders/index', to: 'orders#index'

  get 'emails/index', to: 'emails#index'
  get 'emails/preview', to: 'emails#preview'
  post 'emails/send_email', to: 'emails#send_email'
  post 'emails/send_zero_cater_email', to: 'emails#send_zero_cater_email'

  get 'zero_cater/index', to: 'zero_cater#index'

  get 'roles/index', to: 'roles#index'
  post 'roles/change', to: 'roles#change'
end

app/views/layouts/_navbar.html.haml
#wrapper
  / Header
  %header#header
    .inner
      / Logo
      %a.logo{:href => "index.html"}
        %span.symbol
          = image_tag "temp_imgs/logo.svg"
        %span.title ReferralExchange
      / Nav
      %nav
        %ul
          %li
            = link_to 'Menu', '#menu'
  / Menu
  %nav#menu{style: ''}
    %h2 Rex Eats
    %ul
      %li
        = link_to 'Home', '/restaurants/index'
      - if current_user.try(:has_role?, 'admin')
        %li
          = link_to 'Order History', '/orders/index'
        %li
          = link_to 'Emails', '/emails/index'
        %li
          = link_to 'ZeroCater', '/zero_cater/index'
        %li
          = link_to 'Admin', '/roles/index'
    .bottom-container.text-center
      - if signed_in?
        .bottom-inner.left.display-flex-vertical-center
          Hi #{current_user.username}
        .bottom-inner.left.display-flex-vertical-center
          = button_to 'Log Out', session_destroy_url, method: 'post', class: 'inner-button'
      - else
        .display-flex-vertical-center.max-height
          = button_to 'Sign In', session_new_path, method: 'post', class: 'inner-button'

  :javascript
    $('#new_restaurant_toggle').click(function(e) {
      e.preventDefault();
      $('#new_restaurant_toggle').trigger('showForm');
    });

app/views/layouts/application.html.haml
!!!
%html
  %head
    = favicon_link_tag 'rex-profile-thumb.png'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RexEats
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = render 'layouts/navbar'

  %body
    = yield
    = react_component('NewRestaurant')